const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();
import { Request, Response } from "express";
export default async function insertDb(req: Request, res: Response) {
  try {
    const addData = await prisma.champions.createMany({
      data: [
        {
          driver: "Björn Waldegård",
          driverCountry: "Sweden",
          copilot: "Hans Thorszelius",
          copilotCountry: "Sweden",
          car: "Ford Escort RS1800",
          year: "1979",
        },
        {
          driver: "Walter Röhrl",
          driverCountry: "Germany",
          copilot: "Christian Geistdörfer",
          copilotCountry: "Germany",
          car: "Fiat 131 Abarth",
          year: "1980",
        },
        {
          driver: "Ari Vatanen",
          driverCountry: "Finland",
          copilot: "David Richards",
          copilotCountry: "United Kingdom",
          car: "Ford Escort RS1800",
          year: "1981",
        },
        {
          driver: "Walter Röhrl",
          driverCountry: "Germany",
          copilot: "Christian Geistdörfer",
          copilotCountry: "Germany",
          car: "Opel Ascona 400",
          year: "1982",
        },
        {
          driver: "Hannu Mikkola",
          driverCountry: "Finland",
          copilot: "Arne Hertz",
          copilotCountry: "Sweden",
          car: "Audi Quattro",
          year: "1983",
        },
        {
          driver: "Stig Blomqvist",
          driverCountry: "Sweden",
          copilot: "Björn Cederberg",
          copilotCountry: "Sweden",
          car: "Audi Quattro A2",
          year: "1984",
        },
        {
          driver: "Timo Salonen",
          driverCountry: "Finland",
          copilot: "Seppo Harjanne",
          copilotCountry: "Finland",
          car: "Peugeot 205 Turbo 16 E2",
          year: "1985",
        },
        {
          driver: "Juha Kankkunen",
          driverCountry: "Finland",
          copilot: "Juha Piironen",
          copilotCountry: "Finland",
          car: "Peugeot 205 Turbo 16 E2",
          year: "1986",
        },
        {
          driver: "Juha Kankkunen",
          driverCountry: "Finland",
          copilot: "Juha Piironen",
          copilotCountry: "Finland",
          car: "Lancia Delta HF 4WD",
          year: "1987",
        },
        {
          driver: "Miki Biasion",
          driverCountry: "Italy",
          copilot: "Tiziano Siviero",
          copilotCountry: "Italy",
          car: "Lancia Delta HF 4WD",
          year: "1988",
        },
        {
          driver: "Juha Kankkunen",
          driverCountry: "Finland",
          copilot: "Juha Piironen",
          copilotCountry: "Finland",
          car: "Lancia Delta Integrale 16V",
          year: "1989",
        },
        {
          driver: "Carlos Sainz",
          driverCountry: "Spain",
          copilot: "Luis Moya",
          copilotCountry: "Spain",
          car: "Toyota Celica GT-Four",
          year: "1990",
        },
        {
          driver: "Juha Kankkunen",
          driverCountry: "Finland",
          copilot: "Juha Piironen",
          copilotCountry: "Finland",
          car: "Lancia Delta Integrale",
          year: "1991",
        },
        {
          driver: "Carlos Sainz",
          driverCountry: "Spain",
          copilot: "Luis Moya",
          copilotCountry: "Spain",
          car: "Toyota Celica GT-Four",
          year: "1992",
        },
        {
          driver: "Juha Kankkunen",
          driverCountry: "Finland",
          copilot: "Juha Piironen",
          copilotCountry: "Finland",
          car: "Toyota Celica Turbo 4WD",
          year: "1993",
        },
        {
          driver: "Didier Auriol",
          driverCountry: "France",
          copilot: "Bernard Occelli",
          copilotCountry: "France",
          car: "Toyota Celica Turbo 4WD",
          year: "1994",
        },
        {
          driver: "Colin McRae",
          driverCountry: "United Kingdom",
          copilot: "Derek Ringer",
          copilotCountry: "United Kingdom",
          car: "Subaru Impreza 555",
          year: "1995",
        },
        {
          driver: "Tommi Mäkinen",
          driverCountry: "Finland",
          copilot: "Seppo Harjanne",
          copilotCountry: "Finland",
          car: "Mitsubishi Lancer Evolution III",
          year: "1996",
        },
        {
          driver: "Tommi Mäkinen",
          driverCountry: "Finland",
          copilot: "Seppo Harjanne",
          copilotCountry: "Finland",
          car: "Mitsubishi Lancer Evolution IV",
          year: "1997",
        },
        {
          driver: "Tommi Mäkinen",
          driverCountry: "Finland",
          copilot: "Seppo Harjanne",
          copilotCountry: "Finland",
          car: "Mitsubishi Lancer Evolution V",
          year: "1998",
        },
        {
          driver: "Tommi Mäkinen",
          driverCountry: "Finland",
          copilot: "Risto Mannisenmäki",
          copilotCountry: "Finland",
          car: "Mitsubishi Lancer Evolution VI",
          year: "1999",
        },
        {
          driver: "Marcus Grönholm",
          driverCountry: "Finland",
          copilot: "Timo Rautiainen",
          copilotCountry: "Finland",
          car: "Peugeot 206 WRC",
          year: "2000",
        },
        {
          driver: "Richard Burns",
          driverCountry: "United Kingdom",
          copilot: "Robert Reid",
          copilotCountry: "United Kingdom",
          car: "Subaru Impreza WRC",
          year: "2001",
        },
        {
          driver: "Marcus Grönholm",
          driverCountry: "Finland",
          copilot: "Timo Rautiainen",
          copilotCountry: "Finland",
          car: "Peugeot 206 WRC",
          year: "2002",
        },
        {
          driver: "Petter Solberg",
          driverCountry: "Norway",
          copilot: "Phil Mills",
          copilotCountry: "United Kingdom",
          car: "Subaru Impreza WRC",
          year: "2003",
        },
        {
          driver: "Sebastien Loeb",
          driverCountry: "France",
          copilot: "Daniel Elena",
          copilotCountry: "Monaco",
          car: "Citroën Xsara WRC",
          year: "2004",
        },
        {
          driver: "Sebastien Loeb",
          driverCountry: "France",
          copilot: "Daniel Elena",
          copilotCountry: "Monaco",
          car: "Citroën Xsara WRC",
          year: "2005",
        },
        {
          driver: "Sebastien Loeb",
          driverCountry: "France",
          copilot: "Daniel Elena",
          copilotCountry: "Monaco",
          car: "Citroën C4 WRC",
          year: "2006",
        },
        {
          driver: "Sebastien Loeb",
          driverCountry: "France",
          copilot: "Daniel Elena",
          copilotCountry: "Monaco",
          car: "Citroën C4 WRC",
          year: "2007",
        },
        {
          driver: "Sebastien Loeb",
          driverCountry: "France",
          copilot: "Daniel Elena",
          copilotCountry: "Monaco",
          car: "Citroën C4 WRC",
          year: "2008",
        },
        {
          driver: "Sebastien Loeb",
          driverCountry: "France",
          copilot: "Daniel Elena",
          copilotCountry: "Monaco",
          car: "Citroën C4 WRC",
          year: "2009",
        },
        {
          driver: "Sebastien Loeb",
          driverCountry: "France",
          copilot: "Daniel Elena",
          copilotCountry: "Monaco",
          car: "Citroën DS3 WRC",
          year: "2010",
        },
        {
          driver: "Sebastien Loeb",
          driverCountry: "France",
          copilot: "Daniel Elena",
          copilotCountry: "Monaco",
          car: "Citroën DS3 WRC",
          year: "2011",
        },
        {
          driver: "Sébastien Loeb",
          driverCountry: "France",
          copilot: "Daniel Elena",
          copilotCountry: "Monaco",
          car: "Citroën DS3 WRC",
          year: "2012",
        },
        {
          driver: "Sébastien Ogier",
          driverCountry: "France",
          copilot: "Julien Ingrassia",
          copilotCountry: "France",
          car: "Volkswagen Polo R WRC",
          year: "2013",
        },
        {
          driver: "Sebastien Ogier",
          driverCountry: "France",
          copilot: "Julien Ingrassia",
          copilotCountry: "France",
          car: "Volkswagen Polo R WRC",
          year: "2014",
        },
        {
          driver: "Sebastien Ogier",
          driverCountry: "France",
          copilot: "Julien Ingrassia",
          copilotCountry: "France",
          car: "Volkswagen Polo R WRC",
          year: "2015",
        },
        {
          driver: "Sebastien Ogier",
          driverCountry: "France",
          copilot: "Julien Ingrassia",
          copilotCountry: "France",
          car: "Volkswagen Polo R WRC",
          year: "2016",
        },
        {
          driver: "Sebastien Ogier",
          driverCountry: "France",
          copilot: "Julien Ingrassia",
          copilotCountry: "France",
          car: "Ford Fiesta WRC",
          year: "2017",
        },
        {
          driver: "Sebastien Ogier",
          driverCountry: "France",
          copilot: "Julien Ingrassia",
          copilotCountry: "France",
          car: "Ford Fiesta WRC",
          year: "2018",
        },
        {
          driver: "Ott Tänak",
          driverCountry: "Estonia",
          copilot: "Martin Järveoja",
          copilotCountry: "Estonia",
          car: "Toyota Yaris WRC",
          year: "2019",
        },
        {
          driver: "Ott Tänak",
          driverCountry: "Estonia",
          copilot: "Martin Järveoja",
          copilotCountry: "Estonia",
          car: "Hyundai i20 Coupe WRC",
          year: "2020",
        },
        {
          driver: "Sébastien Ogier",
          driverCountry: "France",
          copilot: "Julien Ingrassia",
          copilotCountry: "France",
          car: "Toyota Yaris WRC",
          year: "2021",
        },
        {
          driver: "Kalle Rovanperä",
          driverCountry: "Finland",
          copilot: "Jonne Halttunen",
          copilotCountry: "Finland",
          car: "Toyota Yaris WRC",
          year: "2022",
        },
        {
          driver: "Kalle Rovanperä",
          driverCountry: "Finland",
          copilot: "SJonne Halttunen",
          copilotCountry: "Finland",
          car: "Toyota Yaris WRC",
          year: "2023",
        },
      ],
    });
    console.log("Champions added", addData);

    return res.status(200).json({ message: "Champions added successfully" });
  } catch (error) {
    console.error("Error adding champions:", error);
    return res.status(500).json({ message: "Internal server error" });
  } finally {
    await prisma.$disconnect();
  }
}
